# Generated by Django 5.0.14 on 2025-10-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mhbot", "0002_moodentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodentry",
            name="mood",
            field=models.CharField(
                choices=[
                    ("great", "great"),
                    ("good", "good"),
                    ("ok", "ok"),
                    ("sad", "sad"),
                    ("down", "down"),
                    ("angry", "angry"),
                    ("anxious", "anxious"),
                    ("stressed", "stressed"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(db_index=True, max_length=64)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("assistant", "assistant"),
                            ("system", "system"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="ai_mhbot_ch_user_id_1cc33f_idx",
                    )
                ],
            },
        ),
    ]
