# Generated by Django 5.0.14 on 2025-10-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mhbot", "0004_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
