# Generated by Django 5.0.14 on 2025-10-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mhbot", "0005_profile_email_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="chat_assistant_text",
            field=models.TextField(blank=True),
        ),
    ]
