# Generated by Django 5.0.14 on 2025-10-31 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mhbot", "0006_moodentry_chat_assistant_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="chat_user_text",
            field=models.TextField(blank=True),
        ),
    ]
