# Generated by Django 5.0.14 on 2025-11-06 17:49

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_mhbot", "0008_loginevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="day",
            field=models.DateField(
                db_index=True, default=django.utils.timezone.localdate
            ),
        ),
        migrations.AddField(
            model_name="moodentry",
            name="session_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="loginevent",
            name="event",
            field=models.CharField(
                choices=[
                    ("login_success", "Login Success"),
                    ("login_failure", "Login Failure"),
                    ("logout", "Logout"),
                    ("signup", "Signup"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="moodentry",
            index=models.Index(
                fields=["user", "created_at"], name="ai_mhbot_mo_user_id_f8a427_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="moodentry",
            index=models.Index(
                fields=["user", "day"], name="ai_mhbot_mo_user_id_8e59e8_idx"
            ),
        ),
    ]
